### ISSUE TITLE
do not check hardcoded for _TtC to _TtCC

### ISSUE THREAD

**Issue by evermeer** [CharlinFeng/Reflect#1]
do not check hardcoded for _TtC to _TtCC
There could be other types than Class.
You could have a _TtCPC
Where P is for Protocol
You can also have functions in there.
So just check for the prefix _T
Then I think you always will have  a t which stands for target of bundle name.
Then continue reading until you hit a number.
The number of characters you have read will be the same as the number of number and string groups that will be after that.

If you have a moment, then later today or tomorrow morning I will add a version of that to https://github.com/evermeer/EVReflection
It's almost done. Im now bug fixing plus creating unit tests for it.

**Comment by evermeer** [comment]
I just pushed my code to GitHub. It's not yet a new cocoa pod version just download the trunk.
There is a TODO in the code for reverse engineering the descriptions for functions.

**Comment by CharlinFeng** [comment]
Learn from you!Mighty big brother!

Reflect’purpose is to complete the class of properties and types in a high degree of encapsulation, as well as a 【powerful and Intelligent dictionary transfer to model】!
